export default {
  'en-US' : {
    'instagram' : 'instagram',
    'question1' : "What's the benefit of holding a CoolTurtle?",
    'question2' : '會跟什麼商家合作？',
    'question3' : '會做什麼公益活動呢？',
    'answer1'   : '跟線下商家合作、實體化、活動、白名單',
    'answer2'   : '台灣全省食衣住行育樂',
    'answer3'   : '有關於海洋保育',

    'footer_lead1':'[獲得方法]',
    'footer_lead2':'[注意事項]',
    'footer_lead3':'[發售時間]',
    'footer_content1':'. CoolTurtle 官方，IG粉專以及官方Discord會發佈CoolTurtle相關活動。 ',
    'footer_content2':'. 註冊交易所與入金購買以太幣需要時間審核，請事前先準備好MetaMask錢包及以太幣。 ',
    'footer_content3':'. 在販售時間前，在MetaMask放入足夠的以太幣，時間到時將會有購買的按鈕，點擊即可開始NFT的鑄造。 ',
    'footer_content4':'. 白單發售鑄造價格:0.08ETH。 ',
    'footer_content5':'. 公開發售鑄造價格:0.1ETH。 ',
    'footer_content6':'. 公開發售將於2022年5月25日08時10分後開始。 ',

  },
  'zh-TW':{
    'instagram' : 'instagram',
    'question1' : '持有CoolTurtle有什麼好處？',
    'question2' : '會跟什麼商家合作？',
    'question3' : '會做什麼公益活動呢？',
    'answer1'   : '跟線下商家合作、實體化、活動、白名單',
    'answer2'   : '台灣全省食衣住行育樂',
    'answer3'   : '有關於海洋保育',

    'footer_lead1':'[獲得方法]',
    'footer_lead2':'[注意事項]',
    'footer_lead3':'[發售時間]',
    'footer_content1':'. CoolTurtle 官方，IG粉專以及官方Discord會發佈CoolTurtle相關活動。 ',
    'footer_content2':'. 註冊交易所與入金購買以太幣需要時間審核，請事前先準備好MetaMask錢包及以太幣。 ',
    'footer_content3':'. 在販售時間前，在MetaMask放入足夠的以太幣，時間到時將會有購買的按鈕，點擊即可開始NFT的鑄造。 ',
    'footer_content4':'. 白單發售鑄造價格:0.08ETH。 ',
    'footer_content5':'. 公開發售鑄造價格:0.1ETH。 ',
    'footer_content6':'. 公開發售將於2022年5月25日08時10分後開始。 ',
  },
}